---
- hosts: windows_rdsh

  vars_files:
    - vars/generic.yml

  roles:
    - { role: ansible-role-win-rdsh }

  # tasks:
  #   - name: generic-rdsh - allow audio and video
  #     win_regedit:
  #       path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'
  #       name: '{{ item }}'
  #       data: 0
  #       type: dword
  #       state: "{{ rdsh_enable_audio_and_video | bool | ternary('present', 'absent') }}"
  #     loop:
  #       - fDisableAudioCapture
  #       - fDisableCam
  #       - fDisableCameraRedir
  #       - fDisablePNPRedir
