name: apply_azfileshares

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TF_VAR_ssh_private_key_pem: ${{ secrets.TF_VAR_ssh_private_key_pem }}

jobs:
  build_job:
    name: build_job
    runs-on: ubuntu-latest

    container:
      image: andif888/docker-pataz:v0.9.9

    steps:

      - name: checkout_repo
        uses: actions/checkout@v3

      - name: show versions in container
        run: |
          ansible --version
          packer --version
          terraform --version
          az --version

      - name: apply_azfileshares
        id: apply_azfileshares
        run: |
          echo -n ${{ secrets.envfile }} > .env && . ./.env
          ./apply_azfileshares.sh

      - name: cleanup_ssh
        if: always()
        run: rm -rf ./.github/.ssh

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "output/rdp/*.rdp"
          bodyFile: "output/README.md"
